"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import type { AssessmentStatus, VetAssessment } from "@/lib/vet/schema";
import { AlertRow, Panel } from "@/components/Panel";
import AssessmentView from "./AssessmentView";

interface Props {
  caseId: string;
  initial: VetAssessment | null;
  initialStatus: AssessmentStatus;
  initialError: string | null;
  hasPhoto: boolean;
  storedSource: string | null;
  liveModel: string;
}

type Mode = "stored" | "loading" | "live" | "saved";

export default function LiveAssessment({ caseId, initial, initialStatus, initialError, hasPhoto, storedSource, liveModel }: Props) {
  const router = useRouter();
  const [assessment, setAssessment] = useState(initial);
  const [mode, setMode] = useState<Mode>("stored");
  const [error, setError] = useState<string | null>(null);

  const rerun = async () => {
    const previous = mode;
    setMode("loading");
    setError(null);
    try {
      const res = await fetch("/api/vet/assess", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ caseId }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error ?? "Something went wrong. Please try again.");
      setAssessment(data.assessment);
      setMode(data.saved ? "saved" : "live");
      // A newly saved assessment changes the header badge and queue, which are server-rendered.
      if (data.saved) router.refresh();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Network error. Please try again.");
      setMode(previous);
    }
  };

  const loading = mode === "loading";
  const failed = !assessment && initialStatus === "failed";

  const sourceLine =
    loading ? `Running a fresh assessment with ${liveModel}. This usually takes under a minute.`
    : mode === "live" ? `Live result from ${liveModel}, generated just now (not saved)`
    : mode === "saved" ? `Generated by ${liveModel} just now and saved to this case`
    : assessment ? `Stored assessment${storedSource ? ` · ${storedSource}` : ""}`
    : failed ? "The automatic assessment didn't complete."
    : "The automatic assessment is still running.";

  const buttonLabel = loading ? "Assessing…" : assessment ? "Re-run AI assessment" : failed ? "Retry assessment" : "Run assessment now";

  return (
    <div>
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", flexWrap: "wrap", gap: 10, marginBottom: "0.3rem" }}>
        <h2 style={{ fontFamily: "'DM Serif Display', serif", fontSize: "1.35rem", fontWeight: 400 }}>AI assessment</h2>
        <button
          onClick={rerun}
          disabled={loading}
          style={{
            display: "inline-flex", alignItems: "center", gap: 8,
            padding: "7px 14px", borderRadius: 10, fontSize: "0.8rem", fontWeight: 500,
            fontFamily: "'DM Sans', sans-serif", cursor: loading ? "wait" : "pointer",
            color: "var(--teal)", background: "var(--teal-dim)", border: "1px solid rgba(20,184,166,0.3)",
            opacity: loading ? 0.7 : 1
          }}
        >
          {loading ? (
            <span style={{
              width: 12, height: 12, borderRadius: "50%", border: "2px solid rgba(20,184,166,0.3)",
              borderTopColor: "var(--teal)", animation: "spin 0.8s linear infinite"
            }} />
          ) : "↻"}
          {buttonLabel}
        </button>
      </div>
      <div style={{ fontSize: "0.72rem", color: mode === "live" || mode === "saved" ? "var(--teal)" : "var(--text3)", marginBottom: "0.8rem" }}>
        {sourceLine}
        {" · "}Decision support only. Confirm with a clinical exam.
      </div>

      {error && <AlertRow type="danger" text={error} />}

      {assessment ? (
        <div style={{ opacity: loading ? 0.4 : 1, transition: "opacity 0.2s", pointerEvents: loading ? "none" : "auto" }}>
          <AssessmentView a={assessment} hasPhoto={hasPhoto} />
        </div>
      ) : (
        <Panel icon={failed ? "⚠️" : "⏳"} iconBg={failed ? "var(--red-dim)" : "var(--bg4)"} title={failed ? "Assessment failed" : "Assessment pending"}>
          <p style={{ fontSize: "0.86rem", color: "var(--text2)", lineHeight: 1.7 }}>
            {failed
              ? "The AI couldn't assess this case automatically. Retry it now; a successful result is saved to the case."
              : "This case was just submitted and the AI is reviewing it. Refresh in a moment, or run it now; the result is saved to the case."}
          </p>
          {failed && initialError && (
            <p style={{ fontSize: "0.78rem", color: "var(--text3)", marginTop: "0.6rem" }}>{initialError}</p>
          )}
        </Panel>
      )}
    </div>
  );
}
